// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(QrDbContext))]
    [Migration("20260213151616_newInit1.0")]
    partial class newInit10
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Context", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ContextPartIsUnique")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTemporary")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("QrToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("contexts");
                });

            modelBuilder.Entity("Domain.Models.ContextPart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContextId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QrToken")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContextId");

                    b.ToTable("contextparts");
                });

            modelBuilder.Entity("Domain.Models.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("owners");
                });

            modelBuilder.Entity("Domain.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Method")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid?>("TabId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TabId");

                    b.HasIndex("UserId");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("Domain.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasMaxLength(500)
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            Name = "Coca Cola",
                            Price = 25.0m,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            Category = "Dryck",
                            Description = "Öl som öl eller?",
                            Name = "Öl",
                            Price = 20.0m,
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            Category = "Dryck",
                            Description = "Le vin rouge pour un amore",
                            Name = "Röd vin",
                            Price = 22.0m,
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            Category = "Dryck",
                            Description = "Fizzy driink",
                            Name = "Sprite",
                            Price = 18.0m,
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            Category = "Dryck",
                            Description = "Still water - tap water",
                            Name = "Water",
                            Price = 10.0m,
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            Category = "Mat",
                            Description = "Nom nom italian pizza, tu veux une piece ou parfois deux pices? ",
                            Name = "Pizza",
                            Price = 30.0m,
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            Category = "Mat",
                            Description = "La pasta - c'est viens en Italie et tres bon",
                            Name = "Pasta",
                            Price = 28.0m,
                            Status = 0
                        },
                        new
                        {
                            Id = 8,
                            Category = "Mat",
                            Description = "La Salade - tres  mais aussie bon et simple no? Avec la fromage et les totmotes",
                            Name = "Salad",
                            Price = 15.0m,
                            Status = 0
                        });
                });

            modelBuilder.Entity("Domain.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PriceEach")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("TabId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("TabId");

                    b.HasIndex("UserId");

                    b.ToTable("transactions");
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Domain.Models.UserTab", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ContextId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContextPartId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContextPartId");

                    b.HasIndex("UserId");

                    b.ToTable("usertabs");
                });

            modelBuilder.Entity("Domain.Models.Context", b =>
                {
                    b.HasOne("Domain.Models.Owner", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Domain.Models.ContextPart", b =>
                {
                    b.HasOne("Domain.Models.Context", "Context")
                        .WithMany("Parts")
                        .HasForeignKey("ContextId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Context");
                });

            modelBuilder.Entity("Domain.Models.Payment", b =>
                {
                    b.HasOne("Domain.Models.UserTab", "Tab")
                        .WithMany("Payments")
                        .HasForeignKey("TabId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Models.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Tab");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.Transaction", b =>
                {
                    b.HasOne("Domain.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Models.UserTab", "Tab")
                        .WithMany("Transactions")
                        .HasForeignKey("TabId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Tab");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.UserTab", b =>
                {
                    b.HasOne("Domain.Models.ContextPart", "ContextPart")
                        .WithMany("UserTabs")
                        .HasForeignKey("ContextPartId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Models.User", "User")
                        .WithMany("Tabs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContextPart");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.Context", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("Domain.Models.ContextPart", b =>
                {
                    b.Navigation("UserTabs");
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Tabs");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Domain.Models.UserTab", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
